# Generated by Django 5.2.7 on 2025-10-23 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=200)),
                ('attackPower', models.IntegerField(default=0)),
                ('defencePower', models.IntegerField(default=1)),
                ('cancelByAttack', models.BooleanField(default=False)),
                ('support', models.BooleanField(default=False)),
                ('move', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('fgcolor', models.CharField(max_length=10)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=5)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tileServer', models.CharField(max_length=100)),
                ('winPoints', models.IntegerField(default=50)),
                ('turnMinutes', models.IntegerField(default=1440)),
                ('status', models.IntegerField(default=0)),
                ('defaultCommandType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.commandtype')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ui.country')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isCity', models.BooleanField(default=False)),
                ('defaultPriority', models.IntegerField(blank=True, default=None, null=True)),
                ('unitPoints', models.IntegerField(default=0)),
                ('winPoints', models.IntegerField(default=0)),
                ('home', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.country')),
                ('next', models.ManyToManyField(blank=True, to='ui.field')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.fieldtype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.game')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.game'),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('newUnits', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.game')),
                ('previous', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.turn')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.country')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.field')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.turn')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.country')),
                ('field', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.field')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.turn')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(blank=True, default='', max_length=100)),
                ('escape', models.CharField(blank=True, default='', max_length=100)),
                ('removePriority', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('commandType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.commandtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('unitPoints', models.IntegerField(default=1)),
                ('fieldTypes', models.ManyToManyField(to='ui.fieldtype')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='unitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.unittype'),
        ),
        migrations.AddField(
            model_name='field',
            name='defaultUnitType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.unittype'),
        ),
        migrations.AddField(
            model_name='commandtype',
            name='unitType',
            field=models.ManyToManyField(blank=True, to='ui.unittype'),
        ),
        migrations.CreateModel(
            name='CityCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('result', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.city')),
                ('newUnitType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.unittype')),
            ],
        ),
    ]
